# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MarvelCharsApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MarvelCharsApp
  pod 'SwiftLint'

  target 'MarvelCharsAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MarvelCharsAppUITests' do
    # Pods for testing
  end

pod 'SideMenu', '~> 6.5.0'

end
